version: "3.7"
services:
  app:
    build:
      args:
        user: pablo
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: censoapp
    container_name: censo-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - censoapp

  db:
    image: mysql:8
    container_name: censo-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - censoapp

  nginx:
    image: nginx:alpine
    container_name: censo-nginx
    restart: unless-stopped
    ports:
      - 8004:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - censoapp

networks:
  censoapp:
    driver: bridge
